server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookex
    username: bookexuser
    password: bookexpassword

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB

app:
  upload-dir: uploads
  max-images-per-listing: 5

  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}

springdoc:
  swagger-ui:
    url: /openapi.yaml
